Add rector rule to remove ray calls from a codebase
spatie/ray pull request #884
Opened 2024-01-09 10:52 UTC by timvandijck

2 ways of using it:

1. In your own Rector config, by adding the `RemoveRayCallRector` rule.
2. By using the package Rector config: `./vendor/bin/remove-ray.sh <path>`

2024-01-09 12:48 UTC, sebastiandedeyne requested changes
Does this also work for chained calls? Like `ray()->clearScreen()` and `ray('Hello')->red()`?

2024-01-09 12:48 UTC, sebastiandedeyne commented on docs/advanced-usage/automatically-remove-ray-calls.md
> +To avoid shipping your code with some ray calls in it you can automate the removal of all ray calls in your codebase.
```suggestion
To avoid shipping your code with some `ray()` calls in it you can automate the removal of all `ray()` calls in your codebase.
```

2024-01-09 12:48 UTC, sebastiandedeyne commented on remove-ray-rector.php
> +
```suggestion
```

2024-01-09 12:48 UTC, sebastiandedeyne commented on src/Rector/RemoveRayCallRector.php
> +        return new RuleDefinition('Remove function', [new ConfiguredCodeSample(<<<'CODE_SAMPLE'
```suggestion
        return new RuleDefinition('Remove Ray calls', [new ConfiguredCodeSample(<<<'CODE_SAMPLE'
```

2024-01-10 10:29 UTC, Plytas commented
And does it also work on macros like `collect()->ray()`?

2024-01-15 10:48 UTC, timvandijck commented
> Does this also work for chained calls? Like `ray()->clearScreen()` and `ray('Hello')->red()`?

> And does it also work on macros like `collect()->ray()`?

Now it should!

2024-01-24 15:28 UTC, merged

2024-01-26 10:32 UTC, Plytas commented
@timvandijck It doesn't seem to remove collection macro `ray()` call.
<img width="1259" alt="image" src="https://github.com/spatie/ray/assets/17316322/81a0eb57-352a-461c-920f-b16a746c3512">

2024-01-26 10:48 UTC, timvandijck commented
@Plytas good spot, it seems like it's not working when a macro line is not ending with ->ray() but with an other method.

I created an issue to track this, probably will be resolved next week: https://github.com/spatie/ray/issues/889